version: '3'

networks:
  user-manager-network:
    driver: bridge
    ipam:
      driver: default

services:
  api:
    container_name: user-manager
    image: user-manager
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=development
      # https://github.com/paulmillr/chokidar
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "9501:9501"
    networks:
      - user-manager-network
  
  redis:
    container_name: user-manager-redis
    image: redis:6.2.6
    ports:
      - 6379:6379
    networks:
      - user-manager-network